name: Android Release

on:
  push:
    tags:
      - 'v*'  # Triggers on tags like v1.0.0, v2.1.3, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create Keystore
        run: |
          echo "${{ secrets.SIGNING_KEYSTORE_BASE64 }}" | base64 --decode > app/keystore.jks

      - name: Create Keystore Properties File
        run: |
          cat <<EOF > keystore.properties
          storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}
          keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
          storeFile=keystore.jks
          EOF

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Rename APK
        run: mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/saorsail.apk

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/saorsail.apk
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
